### ISSUE TITLE
Example use case?

### ISSUE THREAD

**Issue by srl295** [jsahleen/cldr-service#19]
OK i ran login.sh to calculate a bearer token, then:

```
curl -v -X POST -H "Authorization: Bearer ${CLDR_ACCESS_TOKEN}"  'http://127.0.0.1:3000/admin/locales'
```

It might be good to include some example use cases… the 'hello world' equivalent.

**Comment by jsahleen** [comment]
@srl295 This turned out to be a mismatch in the environment variable for the jwt-token. The .env file was updated to have `CLDR_JWT_TOKEN` but I forgot to update the name in the jwt.middleware.ts. Should be working now if you pull the latest image. I will leave this issue open until I have a chance to add an example as you request.

**Comment by jsahleen** [comment]
@srl295 Please see the file `examples/node/antartica.js` for an example using `node-fetch`.
